### ISSUE TITLE
New KF parameter tuning needed

### ISSUE THREAD

**Issue by cgsavard** [cms-L1TK/cmssw#186]
I have come across an issue in the code that causes a crash occasionally. The error message looks like this:
![Uploading image.png…]()

@tschuh Suggests that this requires more tuning of the KF parameters [here](https://github.com/cms-L1TK/cmssw/blob/L1TK-dev-12_5_0_pre2/L1Trigger/TrackerTFP/python/KalmanFilterFormats_cfi.py#L42-L73).

This error can be reproduced by running the new KF on the file root://eoscms.cern.ch//eos/cms/store/relval/CMSSW_12_1_0_pre5/RelValZEE_14/GEN-SIM-DIGI-RAW/PU_121X_mcRun4_realistic_v7_2026D76PU200-v2/2580000/3958677c-3e7e-4a33-85dc-72a8117a435e.root. The crash occurs after event 18.

**Comment by skinnari** [comment]
@cgsavard @tschuh 

I am wondering if this has been fixed or if did anyone look further at these seg faults?

**Comment by tomalin** [comment]
@cgsavard & @tschuh the PNG image of the error message originall uploaded by Claire is no longer available. And without it, I see no chance to debug this. Claire is this crash still happening?
I will close this Issue if I hear nothing in the next 2 weeks.

**Comment by tschuh** [comment]
Sorry for the late reply. It is not a seg fault, it is an cms::Exception which will be thrown when one of the internal integer variables covers not enough range or when squared track parameter uncertainties become negative. For the first case it tells you how to solve it in the second one needs a handle which will be added with PR https://github.com/cms-L1TK/cmssw/pull/205. I believe it was in this instance the first case. I guess this is not urgent since neither I nor Claire had the time to just do it.

**Comment by cgsavard** [comment]
I just attempted to test this again and see if I could reproduce the error but unfortunately, this file can no longer be found. I did find a way around it at the time I believe, but do not remember what I did. I think that it would be okay to close this issue now and then we will see if it pops back up with the new changes that have been made and fix it then.
