### ISSUE TITLE
Fixes desired before making PR to official CMSSW

### ISSUE THREAD

**Issue by tomalin** [cms-L1TK/cmssw#77]
For attention of @aryd:
1) The wires.dat file should not be written to data/LUTs/, since it is not a LUT table. Please change https://github.com/cms-L1TK/cmssw/blob/L1TK-dev-11_3_0_pre3/L1Trigger/TrackFindingTracklet/src/TrackletEventProcessor.cc#L99 to avoid this.
2) The hard-wired constant 0.2 has not yet been eliminated from https://github.com/cms-L1TK/cmssw/blob/L1TK-dev-11_3_0_pre3/L1Trigger/TrackFindingTracklet/src/MatchCalculator.cc#L294
3) Duplicate pin names should be eliminated from wires.dat . e.g. Add "n1", "n2" etc. to distinguish duplicate outputs from different pins. And add "TE"/"ME" to distinguish VMR outputs to TE vs ME.

**Comment by meisonlikesicecream** [comment]
Adding to Ians point 3: it would be nice to also know if it's a TE Outer/Inner as they're separate classes in the HLS? This is not necessary to remove the duplicate pin names, but it would make the wiring easier to read.

**Comment by meisonlikesicecream** [comment]
Think I found a bug in the new wires.dat. For the "extra" TE memories (phi region X,Y,Z or I,J,K etc), the pin names still use the "normal" phi region (A,B,C) for their pin name thus causing more duplicates. I.e:
VMSTE_L2PHIX1n5 input=> VMR_L2PHIA.vmstubout**PHIA**1 output=> TE_L2PHIX1_D1PHIX1.innervmstubin

instead of:
VMSTE_L2PHIX1n1 input=> VMR_L2PHIA.vmstubout**PHIX**1n1  output=> TE_L2PHIX1_D1PHIX1.innervmstubin

The latter is preferred.

**Comment by aryd** [comment]
With the exception of the the first suggestion where the wires.dat file is still written to the data/LUTs directory these comments have been addressed with the changes on the branch: Last1130_updates
